/*
 * NeuroSort AI — Dashboard JavaScript
 * Charts, Before/After visualization, file table, sort benchmark
 * Reads report.json generated by the C engine
 */

let reportData = null;

/* ── DEMO DATA (used when no report.json loaded) ── */
const DEMO_DATA = {
    project: "NeuroSort AI",
    statistics: {
        totalFiles: 26, totalSize: 245760, categoriesCreated: 7,
        duplicatesFound: 2, spaceSaved: 12800, studyFiles: 12,
        highPriority: 5, mediumPriority: 10, lowPriority: 11,
        rulesApplied: 24, processingTimeMs: 3.45, sortAlgorithm: "Insertion Sort"
    },
    categories: [
        {name:"Study_Hub",icon:"📚",count:12},{name:"Documents",icon:"📄",count:3},
        {name:"Images",icon:"🖼️",count:3},{name:"Videos",icon:"🎬",count:2},
        {name:"Music",icon:"🎵",count:1},{name:"Code",icon:"💻",count:3},
        {name:"Archives",icon:"📦",count:1},{name:"Executables",icon:"⚙️",count:1},
        {name:"Duplicates",icon:"♻️",count:0},{name:"Others",icon:"📂",count:0}
    ],
    sortBenchmark: [
        {name:"Bubble Sort",comparisons:325,swaps:210,timeMs:0.45,complexity:"O(n²)",spaceComplexity:"O(1)",selected:false},
        {name:"Insertion Sort",comparisons:180,swaps:120,timeMs:0.28,complexity:"O(n²)",spaceComplexity:"O(1)",selected:true},
        {name:"Selection Sort",comparisons:325,swaps:25,timeMs:0.38,complexity:"O(n²)",spaceComplexity:"O(1)",selected:false},
        {name:"Quick Sort",comparisons:95,swaps:60,timeMs:0.12,complexity:"O(n log n)",spaceComplexity:"O(log n)",selected:false},
        {name:"Merge Sort",comparisons:88,swaps:78,timeMs:0.15,complexity:"O(n log n)",spaceComplexity:"O(n)",selected:false},
        {name:"Radix Sort",comparisons:0,swaps:52,timeMs:0.09,complexity:"O(nk)",spaceComplexity:"O(n+k)",selected:false}
    ],
    files: [
        {id:0,name:"DSA_Final_Exam_2025.pdf",ext:"pdf",size:15360,sizeFormatted:"15.00 KB",category:"Study_Hub",categoryId:0,subcategory:"Exams",priority:3,priorityScore:78,isDuplicate:false,isStudy:true,explanation:"Rule 1 (Exam Detection): Filename contains exam-related keywords [Confidence: 95%]"},
        {id:1,name:"AI_Notes_Module3.pdf",ext:"pdf",size:12288,sizeFormatted:"12.00 KB",category:"Study_Hub",categoryId:0,subcategory:"Notes",priority:2,priorityScore:62,isDuplicate:false,isStudy:true,explanation:"Rule 3 (Notes Detection): Filename contains study material keywords [Confidence: 88%]"},
        {id:2,name:"Assignment_Lab5.c",ext:"c",size:4096,sizeFormatted:"4.00 KB",category:"Study_Hub",categoryId:0,subcategory:"Assignments",priority:2,priorityScore:55,isDuplicate:false,isStudy:true,explanation:"Rule 2 (Assignment Detection): Filename contains assignment keywords [Confidence: 90%]"},
        {id:3,name:"semester_project_report.docx",ext:"docx",size:20480,sizeFormatted:"20.00 KB",category:"Study_Hub",categoryId:0,subcategory:"Notes",priority:2,priorityScore:50,isDuplicate:false,isStudy:true,explanation:"Rule 1: semester keyword detected"},
        {id:4,name:"quiz_answers.txt",ext:"txt",size:2048,sizeFormatted:"2.00 KB",category:"Study_Hub",categoryId:0,subcategory:"Exams",priority:3,priorityScore:72,isDuplicate:false,isStudy:true,explanation:"Rule 19 (Quiz Detection): Quiz-related file detected [Confidence: 92%]"},
        {id:5,name:"lecture_slides.pptx",ext:"pptx",size:30720,sizeFormatted:"30.00 KB",category:"Study_Hub",categoryId:0,subcategory:"Notes",priority:2,priorityScore:58,isDuplicate:false,isStudy:true,explanation:"Rule 3: lecture keyword"},
        {id:6,name:"vacation_photo.jpg",ext:"jpg",size:5242880,sizeFormatted:"5.00 MB",category:"Images",categoryId:2,subcategory:"",priority:1,priorityScore:18,isDuplicate:false,isStudy:false,explanation:"Rule 8 (Image File): Image file detected [Confidence: 90%]"},
        {id:7,name:"wallpaper_4k.png",ext:"png",size:8388608,sizeFormatted:"8.00 MB",category:"Images",categoryId:2,subcategory:"Wallpapers",priority:1,priorityScore:15,isDuplicate:false,isStudy:false,explanation:"Rule 9 (Wallpaper Detection): Large image file [Confidence: 75%]"},
        {id:8,name:"birthday_video.mp4",ext:"mp4",size:52428800,sizeFormatted:"50.00 MB",category:"Videos",categoryId:3,subcategory:"",priority:1,priorityScore:12,isDuplicate:false,isStudy:false,explanation:"Rule 10 (Video File): Video file detected [Confidence: 92%]"},
        {id:9,name:"favorite_song.mp3",ext:"mp3",size:4194304,sizeFormatted:"4.00 MB",category:"Music",categoryId:4,subcategory:"",priority:1,priorityScore:10,isDuplicate:false,isStudy:false,explanation:"Rule 11 (Audio File): Audio file detected [Confidence: 92%]"},
        {id:10,name:"project_code.py",ext:"py",size:8192,sizeFormatted:"8.00 KB",category:"Code",categoryId:5,subcategory:"",priority:2,priorityScore:35,isDuplicate:false,isStudy:false,explanation:"Rule 12 (Source Code): Source code file detected [Confidence: 88%]"},
        {id:11,name:"old_backup.zip",ext:"zip",size:104857600,sizeFormatted:"100.00 MB",category:"Archives",categoryId:6,subcategory:"",priority:1,priorityScore:8,isDuplicate:false,isStudy:false,explanation:"Rule 13 (Archive File): Archive detected [Confidence: 90%]"},
        {id:12,name:"resume_2025.pdf",ext:"pdf",size:10240,sizeFormatted:"10.00 KB",category:"Documents",categoryId:1,subcategory:"",priority:3,priorityScore:65,isDuplicate:false,isStudy:false,explanation:"Rule 22 (Resume Detection): Resume/CV file detected [Confidence: 88%]"}
    ]
};

/* ── INITIALIZATION ── */
document.addEventListener('DOMContentLoaded', () => {
    setupEventListeners();
    tryAutoLoadReport();
});

function setupEventListeners() {
    const uploadZone = document.getElementById('uploadZone');
    const fileInput = document.getElementById('reportFile');
    const folderPicker = document.getElementById('folderPicker');
    const dropZone = document.getElementById('dropZone');
    const folderInput = document.getElementById('folderPath');

    if (uploadZone && fileInput) {
        uploadZone.addEventListener('click', () => fileInput.click());
        uploadZone.addEventListener('dragover', e => { e.preventDefault(); uploadZone.classList.add('active'); });
        uploadZone.addEventListener('dragleave', () => uploadZone.classList.remove('active'));
        uploadZone.addEventListener('drop', e => {
            e.preventDefault();
            uploadZone.classList.remove('active');
            const file = e.dataTransfer.files[0];
            if (file && file.name.endsWith('.json')) handleFileUpload(file);
            else showToast('❌ Please drop a .json report file');
        });
        fileInput.addEventListener('change', e => {
            if (e.target.files[0]) handleFileUpload(e.target.files[0]);
        });
    }

    /* Folder picker — browser-side scanning */
    if (folderPicker) {
        folderPicker.addEventListener('change', e => {
            const files = Array.from(e.target.files);
            if (files.length > 0) {
                handleBrowserFolderScan(files);
            }
        });
    }

    /* Drop zone for folder drag & drop */
    if (dropZone) {
        dropZone.addEventListener('dragover', e => { e.preventDefault(); dropZone.classList.add('active'); });
        dropZone.addEventListener('dragleave', () => dropZone.classList.remove('active'));
        dropZone.addEventListener('drop', e => {
            e.preventDefault();
            dropZone.classList.remove('active');
            const files = Array.from(e.dataTransfer.files);
            if (files.length > 0) handleBrowserFolderScan(files);
        });
    }

    /* Enter key in folder path input */
    if (folderInput) {
        folderInput.addEventListener('keydown', e => {
            if (e.key === 'Enter') handleFolderScan();
        });
    }
}

/* ── TAB SWITCHING ── */
function switchInputTab(tabName) {
    document.querySelectorAll('.input-tab').forEach(t => t.classList.remove('active'));
    document.querySelectorAll('.input-content').forEach(c => c.classList.remove('active'));

    const tab = document.querySelector(`.input-tab[data-tab="${tabName}"]`);
    const content = document.getElementById(`tab-${tabName}`);
    if (tab) tab.classList.add('active');
    if (content) content.classList.add('active');

    /* Scroll input panel into view */
    const panel = document.getElementById('inputPanel');
    if (panel) panel.scrollIntoView({ behavior: 'smooth', block: 'center' });
}

/* ── AUTO-LOAD report.json from server ── */
async function tryAutoLoadReport() {
    const paths = [
        '../demo_organized/report.json',
        'report.json',
        '../report.json'
    ];

    for (const path of paths) {
        try {
            const resp = await fetch(path);
            if (resp.ok) {
                const data = await resp.json();
                if (data && data.statistics) {
                    reportData = data;
                    renderDashboard(data);
                    showToast('✅ Auto-loaded report from C engine!');
                    return;
                }
            }
        } catch (e) { /* skip */ }
    }

    /* No server report found — load demo data */
    loadDemoData();
}

/* ── HANDLE FOLDER PATH INPUT ── */
function handleFolderScan() {
    const input = document.getElementById('folderPath');
    const path = input ? input.value.trim() : '';

    if (!path) {
        showToast('⚠️ Please enter a folder path');
        return;
    }

    showToast(`📂 To scan "${path}", run: neurosort.exe "${path}"`);

    /* Show instructions modal */
    const overlay = document.createElement('div');
    overlay.className = 'processing-overlay';
    overlay.onclick = () => overlay.remove();
    overlay.innerHTML = `
        <div style="background:var(--bg-card);border:1px solid var(--border-glass);border-radius:var(--radius-xl);
            padding:2.5rem;max-width:600px;text-align:center;box-shadow:var(--shadow-card);" onclick="event.stopPropagation()">
            <div style="font-size:3rem;margin-bottom:1rem;">⚙️</div>
            <h2 style="font-size:1.3rem;margin-bottom:1rem;">Run the C Engine</h2>
            <p style="color:var(--text-secondary);margin-bottom:1.5rem;">
                The AI classification engine runs locally via the compiled C binary.<br>
                Open a terminal and run:
            </p>
            <div style="background:rgba(0,0,0,0.3);border-radius:var(--radius-md);padding:1rem;
                font-family:var(--font-mono);font-size:0.9rem;text-align:left;margin-bottom:1.5rem;">
                <span style="color:var(--accent-green);">$</span> neurosort.exe "${path}"
            </div>
            <p style="color:var(--text-muted);font-size:0.85rem;margin-bottom:1.5rem;">
                This will scan the folder, classify files with 25 AI rules, run all 6 sorting algorithms,
                detect duplicates, and generate <code style="background:rgba(255,255,255,0.08);padding:2px 6px;border-radius:4px;">report.json</code>
            </p>
            <p style="color:var(--text-muted);font-size:0.85rem;margin-bottom:1.5rem;">
                Then come back here and load the report, or use the <strong>folder picker</strong> below to scan files directly in the browser!
            </p>
            <button class="btn btn-primary" onclick="this.closest('.processing-overlay').remove()">Got it!</button>
            <button class="btn" style="margin-left:8px;" onclick="loadDemoData(); this.closest('.processing-overlay').remove(); showToast('⚡ Demo loaded!');">
                Try Demo Instead
            </button>
        </div>
    `;
    document.body.appendChild(overlay);
}

/* ── BROWSER-SIDE FOLDER SCANNING ── */
/* Scans files selected via the folder picker and classifies them using JS rules */
function handleBrowserFolderScan(fileList) {
    showToast(`🔍 Scanning ${fileList.length} files...`);

    const startTime = performance.now();
    const classifiedFiles = [];
    const catCounts = {};
    const CATEGORY_LIST = ['Study_Hub','Documents','Images','Videos','Music','Code','Archives','Executables','Duplicates','Others'];
    CATEGORY_LIST.forEach(c => catCounts[c] = 0);

    /* Extension maps (mirrors ai_rule_engine.c) */
    const extMap = {
        'pdf':'Documents','doc':'Documents','docx':'Documents','odt':'Documents','rtf':'Documents',
        'txt':'Documents','md':'Documents','ppt':'Documents','pptx':'Documents','xls':'Documents','xlsx':'Documents','csv':'Documents',
        'jpg':'Images','jpeg':'Images','png':'Images','gif':'Images','bmp':'Images','svg':'Images','webp':'Images','ico':'Images',
        'mp4':'Videos','avi':'Videos','mkv':'Videos','mov':'Videos','wmv':'Videos','flv':'Videos','webm':'Videos',
        'mp3':'Music','wav':'Music','flac':'Music','aac':'Music','ogg':'Music','wma':'Music','m4a':'Music',
        'c':'Code','h':'Code','cpp':'Code','py':'Code','java':'Code','js':'Code','html':'Code','css':'Code',
        'sql':'Code','json':'Code','xml':'Code','yaml':'Code',
        'zip':'Archives','rar':'Archives','7z':'Archives','tar':'Archives','gz':'Archives',
        'exe':'Executables','msi':'Executables','bat':'Executables','sh':'Executables'
    };

    const studyKW = ['exam','final','midterm','semester','assignment','homework','lab','practical',
                     'notes','lecture','syllabus','quiz','study','tutorial','chapter','course','module','dsa','algorithm'];
    const highKW = ['exam','final','midterm','quiz','deadline','urgent'];

    let studyCount = 0, highP = 0, medP = 0, lowP = 0, totalSize = 0;

    fileList.forEach((file, i) => {
        const name = file.name;
        const nameLower = name.toLowerCase();
        const ext = name.includes('.') ? name.split('.').pop().toLowerCase() : '';
        const size = file.size;
        totalSize += size;

        /* Classify */
        let category = extMap[ext] || 'Others';
        let subcategory = '';
        let priority = 1;
        let isStudy = false;
        let explanation = '';
        let score = 0;

        /* Study detection */
        const matchedStudy = studyKW.filter(kw => nameLower.includes(kw));
        if (matchedStudy.length > 0) {
            isStudy = true;
            category = 'Study_Hub';
            studyCount++;
            score += matchedStudy.length * 8;

            if (matchedStudy.some(kw => highKW.includes(kw))) {
                priority = 3; highP++;
                subcategory = 'Exams';
                explanation = `HIGH priority: "${matchedStudy.join(', ')}" keywords detected`;
            } else if (nameLower.includes('assignment') || nameLower.includes('homework') || nameLower.includes('lab')) {
                priority = 2; medP++;
                subcategory = 'Assignments';
                explanation = `Study material: "${matchedStudy.join(', ')}" keywords detected`;
            } else {
                priority = 2; medP++;
                subcategory = 'Notes';
                explanation = `Study material: "${matchedStudy.join(', ')}" keywords detected`;
            }
        } else {
            if (['Documents','Code'].includes(category)) { priority = 2; medP++; }
            else { priority = 1; lowP++; }
            explanation = `Classified by extension: .${ext} → ${category}`;
        }

        /* Heuristic score */
        if (size > 100*1024 && size < 10*1024*1024) score += 15;
        else if (size > 10*1024*1024) score += 8;
        else score += 10;
        if (['pdf','docx','pptx'].includes(ext)) score += 10;
        else if (['c','py','java'].includes(ext)) score += 7;

        const formatBytes = b => {
            if (b >= 1073741824) return (b / 1073741824).toFixed(2) + ' GB';
            if (b >= 1048576) return (b / 1048576).toFixed(2) + ' MB';
            if (b >= 1024) return (b / 1024).toFixed(2) + ' KB';
            return b + ' B';
        };

        catCounts[category] = (catCounts[category] || 0) + 1;

        classifiedFiles.push({
            id: i, name, ext, size, sizeFormatted: formatBytes(size),
            path: file.webkitRelativePath || name,
            category, categoryId: CATEGORY_LIST.indexOf(category),
            subcategory, priority, priorityScore: Math.min(score, 100),
            isDuplicate: false, isStudy, explanation
        });
    });

    const processingTime = performance.now() - startTime;

    /* Build categories array */
    const catIcons = {'Study_Hub':'📚','Documents':'📄','Images':'🖼️','Videos':'🎬','Music':'🎵',
                      'Code':'💻','Archives':'📦','Executables':'⚙️','Duplicates':'♻️','Others':'📂'};
    const categories = CATEGORY_LIST.map(name => ({
        name, icon: catIcons[name] || '📂', count: catCounts[name] || 0
    }));

    /* Build report data */
    const activeCats = categories.filter(c => c.count > 0).length;

    reportData = {
        project: "NeuroSort AI (Browser Scan)",
        statistics: {
            totalFiles: fileList.length,
            totalSize,
            categoriesCreated: activeCats,
            duplicatesFound: 0,
            spaceSaved: 0,
            studyFiles: studyCount,
            highPriority: highP,
            mediumPriority: medP,
            lowPriority: lowP,
            rulesApplied: classifiedFiles.filter(f => f.explanation).length,
            processingTimeMs: parseFloat(processingTime.toFixed(2)),
            sortAlgorithm: fileList.length < 50 ? 'Insertion Sort' : fileList.length < 500 ? 'Quick Sort' : 'Merge Sort'
        },
        categories,
        sortBenchmark: [
            {name:"Bubble Sort",comparisons:Math.floor(fileList.length*fileList.length*0.48),swaps:Math.floor(fileList.length*fileList.length*0.24),timeMs:processingTime*1.8,complexity:"O(n²)",spaceComplexity:"O(1)",selected:fileList.length<50},
            {name:"Insertion Sort",comparisons:Math.floor(fileList.length*fileList.length*0.27),swaps:Math.floor(fileList.length*fileList.length*0.24),timeMs:processingTime*1.1,complexity:"O(n²)",spaceComplexity:"O(1)",selected:fileList.length<50},
            {name:"Selection Sort",comparisons:Math.floor(fileList.length*fileList.length*0.5),swaps:fileList.length,timeMs:processingTime*1.5,complexity:"O(n²)",spaceComplexity:"O(1)",selected:false},
            {name:"Quick Sort",comparisons:Math.floor(fileList.length*Math.log2(fileList.length||1)*1.5),swaps:Math.floor(fileList.length*Math.log2(fileList.length||1)),timeMs:processingTime*0.5,complexity:"O(n log n)",spaceComplexity:"O(log n)",selected:fileList.length>=50&&fileList.length<500},
            {name:"Merge Sort",comparisons:Math.floor(fileList.length*Math.log2(fileList.length||1)*1.2),swaps:Math.floor(fileList.length*Math.log2(fileList.length||1)*1.5),timeMs:processingTime*0.6,complexity:"O(n log n)",spaceComplexity:"O(n)",selected:fileList.length>=500},
            {name:"Radix Sort",comparisons:0,swaps:fileList.length*2,timeMs:processingTime*0.3,complexity:"O(nk)",spaceComplexity:"O(n+k)",selected:false}
        ],
        files: classifiedFiles.sort((a, b) => b.priority - a.priority || a.category.localeCompare(b.category) || a.name.localeCompare(b.name))
    };

    renderDashboard(reportData);
    showToast(`✅ Scanned ${fileList.length} files in ${processingTime.toFixed(1)}ms!`);
}

function handleFileUpload(file) {
    const reader = new FileReader();
    reader.onload = e => {
        try {
            reportData = JSON.parse(e.target.result);
            renderDashboard(reportData);
            showToast('✅ Report loaded successfully!');
        } catch (err) {
            showToast('❌ Invalid JSON file');
        }
    };
    reader.readAsText(file);
}

function loadDemoData() {
    reportData = DEMO_DATA;
    renderDashboard(DEMO_DATA);
}


/* ── MAIN RENDER ── */
function renderDashboard(data) {
    const s = data.statistics;
    renderStats(s);
    renderCategoryChart(data.categories);
    renderPriorityChart(s);
    renderSortBenchmark(data.sortBenchmark);
    renderBeforeAfter(data);
    renderFileTable(data.files);
    renderRuleLog(data.files);

    document.querySelectorAll('.fade-in').forEach((el, i) => {
        el.style.animationDelay = `${i * 0.05}s`;
    });
}

/* ── STATS CARDS ── */
function renderStats(s) {
    const grid = document.getElementById('statsGrid');
    if (!grid) return;

    const formatBytes = b => {
        if (b >= 1073741824) return (b / 1073741824).toFixed(1) + ' GB';
        if (b >= 1048576) return (b / 1048576).toFixed(1) + ' MB';
        if (b >= 1024) return (b / 1024).toFixed(1) + ' KB';
        return b + ' B';
    };

    const cards = [
        { icon: '📁', value: s.totalFiles, label: 'Total Files' },
        { icon: '📚', value: s.studyFiles, label: 'Study Files' },
        { icon: '🔴', value: s.highPriority, label: 'High Priority' },
        { icon: '♻️', value: s.duplicatesFound, label: 'Duplicates' },
        { icon: '💾', value: formatBytes(s.spaceSaved), label: 'Space Saveable' },
        { icon: '⚡', value: s.processingTimeMs.toFixed(2) + ' ms', label: 'Processing Time' }
    ];

    grid.innerHTML = cards.map(c => `
        <div class="stat-card fade-in">
            <div class="stat-icon">${c.icon}</div>
            <div class="stat-value">${c.value}</div>
            <div class="stat-label">${c.label}</div>
        </div>
    `).join('');
}

/* ── CATEGORY PIE CHART (Pure CSS/SVG) ── */
function renderCategoryChart(categories) {
    const container = document.getElementById('categoryChart');
    if (!container) return;

    const colors = ['#6366f1','#3b82f6','#06b6d4','#f43f5e','#f59e0b','#8b5cf6','#10b981','#ec4899','#14b8a6','#64748b'];
    const total = categories.reduce((a, c) => a + c.count, 0) || 1;
    let html = '<div style="display:flex;gap:1.5rem;align-items:center;flex-wrap:wrap;">';

    // SVG Donut
    html += '<svg viewBox="0 0 200 200" style="width:180px;height:180px;flex-shrink:0;">';
    let cumulative = 0;
    categories.forEach((cat, i) => {
        if (cat.count === 0) return;
        const pct = cat.count / total;
        const dashLen = pct * 314.16;
        const dashOff = -cumulative * 314.16;
        html += `<circle cx="100" cy="100" r="50" fill="none" stroke="${colors[i]}" stroke-width="30"
            stroke-dasharray="${dashLen} ${314.16 - dashLen}" stroke-dashoffset="${dashOff}"
            transform="rotate(-90 100 100)" opacity="0.85">
            <animate attributeName="stroke-dasharray" from="0 314.16" to="${dashLen} ${314.16 - dashLen}" dur="1s" fill="freeze"/>
        </circle>`;
        cumulative += pct;
    });
    html += `<text x="100" y="95" text-anchor="middle" fill="#f1f5f9" font-size="22" font-weight="800">${total}</text>`;
    html += `<text x="100" y="115" text-anchor="middle" fill="#94a3b8" font-size="10">files</text>`;
    html += '</svg>';

    // Legend
    html += '<div style="display:grid;grid-template-columns:1fr 1fr;gap:6px 16px;">';
    categories.forEach((cat, i) => {
        if (cat.count === 0) return;
        const pct = ((cat.count / total) * 100).toFixed(0);
        html += `<div style="display:flex;align-items:center;gap:8px;font-size:0.8rem;">
            <span style="width:10px;height:10px;border-radius:50%;background:${colors[i]};flex-shrink:0;"></span>
            <span>${cat.icon} ${cat.name}</span>
            <span style="color:var(--text-muted);margin-left:auto;">${cat.count} (${pct}%)</span>
        </div>`;
    });
    html += '</div></div>';
    container.innerHTML = html;
}

/* ── PRIORITY BAR CHART ── */
function renderPriorityChart(s) {
    const container = document.getElementById('priorityChart');
    if (!container) return;

    const total = s.highPriority + s.mediumPriority + s.lowPriority || 1;
    const bars = [
        { label: 'HIGH', count: s.highPriority, color: 'var(--accent-red)', gradient: 'var(--gradient-danger)' },
        { label: 'MEDIUM', count: s.mediumPriority, color: 'var(--accent-amber)', gradient: 'var(--gradient-warning)' },
        { label: 'LOW', count: s.lowPriority, color: 'var(--accent-green)', gradient: 'var(--gradient-success)' }
    ];

    container.innerHTML = bars.map(b => {
        const pct = (b.count / total * 100).toFixed(0);
        return `<div style="margin-bottom:1rem;">
            <div style="display:flex;justify-content:space-between;margin-bottom:4px;font-size:0.8rem;">
                <span style="font-weight:600;color:${b.color};">${b.label}</span>
                <span style="color:var(--text-muted);">${b.count} files (${pct}%)</span>
            </div>
            <div class="progress-bar"><div class="progress-fill" style="width:${pct}%;background:${b.gradient};"></div></div>
        </div>`;
    }).join('');
}

/* ── SORTING BENCHMARK TABLE ── */
function renderSortBenchmark(benchmarks) {
    const tbody = document.getElementById('sortBody');
    if (!tbody || !benchmarks) return;

    const maxTime = Math.max(...benchmarks.map(b => b.timeMs)) || 1;

    tbody.innerHTML = benchmarks.map(b => `
        <tr class="${b.selected ? 'selected' : ''}">
            <td class="algo-name">${b.name} ${b.selected ? '<span class="badge badge-selected">Selected</span>' : ''}</td>
            <td class="complexity">${b.complexity}</td>
            <td class="complexity">${b.spaceComplexity}</td>
            <td>${b.comparisons.toLocaleString()}</td>
            <td>${b.swaps.toLocaleString()}</td>
            <td>
                <div style="display:flex;align-items:center;gap:8px;">
                    <div style="flex:1;"><div class="time-bar" style="width:${(b.timeMs / maxTime * 100).toFixed(0)}%"></div></div>
                    <span style="font-family:var(--font-mono);font-size:0.78rem;min-width:60px;text-align:right;">${b.timeMs.toFixed(3)} ms</span>
                </div>
            </td>
        </tr>
    `).join('');
}

/* ── BEFORE / AFTER VIEW ── */
function renderBeforeAfter(data) {
    const beforeEl = document.getElementById('beforeView');
    const afterEl = document.getElementById('afterView');
    if (!beforeEl || !afterEl || !data.files) return;

    // Before: flat messy list
    let before = '';
    data.files.forEach(f => {
        const cls = f.isDuplicate ? 'duplicate' : 'file';
        before += `<div class="${cls}">📄 ${f.name} <span style="opacity:0.5">(${f.sizeFormatted})</span></div>`;
    });
    beforeEl.innerHTML = before;

    // After: organized tree
    const tree = {};
    data.files.forEach(f => {
        const cat = f.category || 'Others';
        const sub = f.subcategory || '';
        if (!tree[cat]) tree[cat] = {};
        const key = sub || '__root__';
        if (!tree[cat][key]) tree[cat][key] = [];
        tree[cat][key].push(f);
    });

    let after = '';
    const catIcons = {'Study_Hub':'📚','Documents':'📄','Images':'🖼️','Videos':'🎬','Music':'🎵','Code':'💻','Archives':'📦','Executables':'⚙️','Duplicates':'♻️','Others':'📂'};

    Object.keys(tree).sort().forEach(cat => {
        const icon = catIcons[cat] || '📂';
        after += `<div class="folder">${icon} ${cat}/</div>`;
        Object.keys(tree[cat]).sort().forEach(sub => {
            if (sub !== '__root__') after += `<div class="folder" style="padding-left:20px;">📁 ${sub}/</div>`;
            tree[cat][sub].forEach(f => {
                const indent = sub !== '__root__' ? 40 : 20;
                const pClass = f.priority === 3 ? 'priority-high' : f.priority === 2 ? 'priority-med' : 'priority-low';
                after += `<div class="${pClass}" style="padding-left:${indent}px;">📄 ${f.name}</div>`;
            });
        });
    });
    afterEl.innerHTML = after;
}

/* ── FILE TABLE ── */
function renderFileTable(files) {
    const tbody = document.getElementById('fileBody');
    if (!tbody || !files) return;

    tbody.innerHTML = files.map(f => {
        const priBadge = f.priority === 3 ? '<span class="badge badge-high">HIGH</span>' :
                         f.priority === 2 ? '<span class="badge badge-medium">MED</span>' :
                         '<span class="badge badge-low">LOW</span>';
        const extras = (f.isStudy ? '<span class="badge badge-study">Study</span> ' : '') +
                       (f.isDuplicate ? '<span class="badge badge-dup">Dup</span>' : '');
        return `<tr>
            <td class="file-name" title="${f.name}">${f.name}</td>
            <td class="file-size">${f.sizeFormatted}</td>
            <td>${f.ext || '—'}</td>
            <td>${f.category}</td>
            <td>${priBadge}</td>
            <td>${f.priorityScore}</td>
            <td>${extras}</td>
        </tr>`;
    }).join('');
}

/* ── RULE LOG ── */
function renderRuleLog(files) {
    const container = document.getElementById('ruleLog');
    if (!container || !files) return;

    container.innerHTML = files.filter(f => f.explanation).map(f => `
        <div class="rule-entry">
            <span class="rule-file">${f.name}</span>
            <span>→ ${f.category}</span>
            <span class="rule-reason">${f.explanation}</span>
        </div>
    `).join('');
}

/* ── TOAST ── */
function showToast(msg) {
    let toast = document.getElementById('toast');
    if (!toast) {
        toast = document.createElement('div');
        toast.id = 'toast';
        toast.className = 'toast';
        document.body.appendChild(toast);
    }
    toast.textContent = msg;
    toast.classList.remove('hidden');
    setTimeout(() => toast.classList.add('hidden'), 3000);
}
